# Generated by Django 4.1 on 2023-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_fotografia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
